# Adapted from https://github.com/bsmurphy/PyKrige/blob/master/appveyor.yml
build: false

environment:
  global:
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      # Used by atropy ci-helpers
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      REQUIREMENTS_FILE: "requirements.txt"
      PYTEST_PATH: "freediscovery/tests/"

    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      REQUIREMENTS_FILE: "requirements_engine.txt"
      PYTEST_PATH: "."

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - conda config --append channels conda-forge
  - conda install -y --file %REQUIREMENTS_FILE%
  - pip install nose pytest
  - pip install -e .

test_script:
  - pytest -sv %PYTEST_PATH%
  - conda install -y matplotlib==2.2.3
  - ps: | 
          cd ".\\examples\\python"
          Get-ChildItem ".\\" -Filter *.py | 
          Foreach-Object {
              python $_.FullName 2>&1 | Tee-Object -Append -FilePath "C:\\log.txt"
          }


          if ($PYTHON_VERSION -eq 3.6 ) {
              # install matplotlib which we don't add as a core dependency but which is used in examples
              # now start the server and run the examples
              Start-Process -FilePath "freediscovery" -ArgumentList "run -y --cache-dir ..\\freediscovery_shared" -WorkingDirectory ".\\" -Verbose
              
              cd "..\\engine"
              Get-ChildItem ".\\" -Filter *.py | 
              Foreach-Object {
                  python $_.FullName 2>&1 | Tee-Object -Append -FilePath "C:\\log.txt"
              }
              type "..\\..\\..\\freediscovery_shared\\freediscovery-backend.log"
              if (sls "Traceback \(most recent call last\):" "..\\..\\..\\freediscovery_shared\\freediscovery-backend.log"  -ca -quiet) {
                  exit 1
              }
          } 
          type "C:\\log.txt"
          if (sls "Traceback \(most recent call last\):" "C:\\log.txt" -ca -quiet) {
              exit 1
          }
          

